const Inventory  = [
    {
        id: 0,
        category: "tools",
        name: "Shovel",
        variant: null,
        unitPrice: 2500,
        src: "https://static.wikia.nocookie.net/animalcrossing/images/0/0f/NH-Shovel.png",
        quantity: 0,
        subTotal: 0,
    },
    {
        id: 1,
        category: "tools",
        name: "Watering Can",
        variant: null,
        unitPrice: 2400,
        src: "https://static.wikia.nocookie.net/animalcrossing/images/a/ad/NH-Watering_can.png",
        quantity: 0,
        subTotal: 0,
    },
    {
        id: 2,
        category: "tools",
        name: "Axe",
        variant: null,
        unitPrice: 2500,
        src: "https://static.wikia.nocookie.net/animalcrossing/images/6/68/NH-Tools-Axe.png",
        quantity: 0,
        subTotal: 0,
    },
    {
        id: 3,
        category: "tools",
        name: "Fishing Rod",
        variant: null,
        unitPrice: 2500,
        src: "https://dodo.ac/np/images/a/a1/Fishing_Rod_%28Blue%29_NH_Icon.png",
        quantity: 0,
        subTotal: 0,
    },
    {
        id: 4,
        category: "seasonal",
        name: "Big Festive Tree",
        variant: null,
        unitPrice: 3200,
        src: "https://static.wikia.nocookie.net/animalcrossing/images/a/a7/NH-DIY-Furniture-Big_festive_tree.png",
        quantity: 0,
        subTotal: 0,
    },
    {
        id: 5,
        category: "seasonal",
        name: "Holiday Candle",
        variant: null,
        unitPrice: 1500,
        src: "https://static.wikia.nocookie.net/animalcrossing/images/2/24/NH-DIY-Furniture-Holiday_candle.png",
        quantity: 0,
        subTotal: 0,
    },
    {
        id: 6,
        category: "furniture",
        name: "Double Sofa",
        variant: null,
        unitPrice: 4300,
        src: "https://dodo.ac/np/images/0/0d/Double_Sofa_%28Dark_Brown%29_NH_Icon.png",
        quantity: 0,
        subTotal: 0,
    },
    {
        id: 7,
        category: "furniture",
        name: "Diner Sign",
        variant: null,
        unitPrice: 3900,
        src: "https://dodo.ac/np/images/1/1d/Diner_Neon_Sign_%28Green%29_NH_Icon.png",
        quantity: 0,
        subTotal: 0,
    },
    {
        id: 8,
        category: "furniture",
        name: "Pinball Machine",
        variant: null,
        unitPrice: 2700,
        src: "https://dodo.ac/np/images/e/e2/Pinball_Machine_%28Red%29_NH_Icon.png",
        quantity: 0,
        subtTotal: 0,
    },
    {
        id: 9,
        category: "furniture",
        name: "Wood-burning Stove",
        variant: null,
        unitPrice: 2100,
        src: "https://dodo.ac/np/images/6/62/Wood-Burning_Stove_NH_Icon.png",
        quantity: 0,
        subTotal: 0,
    },
    // {
    //     id: 10,
    //     category: "gear",
    //     name: "Quaffle",
    //     variant: null,
    //     unitPrice: 3,
    //     src: "https://images-na.ssl-images-amazon.com/images/I/41AXmVo5nWL._AC_SX466_.jpg",
    //     quantity: 0,
        // subtTotal: 0,
    // },
    // {
    //     id: 11,
    //     category: "gear",
    //     name: "Golden Snitch",
    //     variant: null,
    //     unitPrice: 3,
    //     src: "https://assets.ptimgs.com/ptimgs/ab/images/dp/wcm/202040/0236/harry-potter-golden-snitch-clock-c.jpg",
    //     quantity: 0,
    //     subTotal: 0,
    // },
  ]
  
  export default Inventory;